---
- name: install redis_commander
  command: "{{ nodejs['home_dir'] }}/bin/npm install -g redis-commander"
  register: install_npm

- fail: failure install npm
  when: install_npm|changed and install_npm.stdout.find('npm not ok') != -1