- name: install dependencies
  apt: name={{item}} state=present
  with_items:
    - pkg-config
    - python
    - unzip

- name: prepare group
  group: name=storm state=present

- name: prepare user
  user: name=storm group=storm comment="storm user" state=present

- name: fetch
  get_url: url={{ storm['url'] }} dest={{ storm['archive'] }}

- name: unpack
  command: chdir={{ install_dir }} unzip {{ storm['archive'] }} creates={{ storm['home_dir'] }}

- name: symlink
  file: src={{ storm['home_dir'] }} dest={{ storm['link'] }} owner=storm group=storm state=link

- name: create dir /logs
  file: path={{ storm['home_dir'] }}/logs owner=storm group=storm recurse=yes state=directory

- name: link local log dir to /var/log/storm
  file: src={{ storm['home_dir'] }}/logs dest={{ storm['log_dir'] }} owner=storm group=storm state=link

- name: create dir /conf
  file: path={{ storm['home_dir'] }}/conf owner=storm group=storm recurse=yes state=directory

- name: recurse change permissions
  file: path={{ storm['home_dir'] }} owner=storm group=storm recurse=yes state=directory