- name: install
  apt: pkg=java7-jdk state=present

- name: add JAVA_HOME to PATH
  template: src=profile.d/java.sh.j2 dest=/etc/profile.d/java.sh mode=777

- name: read JAVA_HOME
  command: bash /etc/profile.d/java.sh
