---
- include: webupd8.yml

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  changed_when: false

- name: Install Oracle Java
  apt: pkg={{ item }} state=present
  when: item|search("^oracle")
  with_items: java['version']
