---
- name: Add the webupd8 APT repository key
  apt_key: data="{{ lookup('file', 'webupd8.key.asc') }}" state=present

- name: Add the webupd8 APT repository
  apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" state=present
