tmp_dir: /tmp
install_dir: /opt
redis_version: 2.8.12

redis:
  url: http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz
  archive: "{{ tmp_dir }}/redis-{{ redis_version }}.tar.gz"
  home_dir: "{{ install_dir }}/redis-{{ redis_version }}"
  bin_dir: "{{ install_dir }}/redis-{{ redis_version }}/bin"

  group: redis
  user: redis
