tmp_dir: /tmp
install_dir: /opt
redis_version: 2.8.12

redis:
  url: http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz
  archive: "{{ tmp_dir }}/redis-{{ redis_version }}.tar.gz"
  home_dir: "{{ install_dir }}/redis-{{ redis_version }}"
  src_dir: "{{ install_dir }}/redis-{{ redis_version }}/src"
  bin_dir: "{{ install_dir }}/redis-{{ redis_version }}/bin"
  log_dir: "{{ install_dir }}/redis-{{ redis_version }}/log"
  data_dir: "{{ install_dir }}/redis-{{ redis_version }}/data"

  port: 6379
  maxmemory: "{{ (ansible_memtotal_mb * 1024 * 1024 * 0.8)|int }}"

  message_test_passed: 'All tests passed without errors!'
  path_test_passed: "{{ install_dir }}/redis-{{ redis_version }}/.tests_passed"

  group: redis
  user: redis
