- name: prepare group
  group: name=kafka state=present

- name: prepare user
  user: name=kafka group=kafka comment="kafka" state=present

- name: fetch
  get_url: url={{ kafka['url'] }} dest={{ kafka['archive'] }} creates={{ kafka['archive'] }}

- name: unpack
  command: chdir={{ install_dir }} tar xf {{ kafka['archive'] }} creates={{ kafka['home_dir'] }}

- name: fetch
  get_url: url={{ kafka['url'] }} dest={{ kafka['archive'] }}

- name: symlink
  file: src={{ kafka['home_dir'] }} dest={{ kafka['link'] }} owner=kafka group=kafka state=link

- name: gradle jar
  command: chdir={{ kafka['home_dir'] }} ./gradlew jar creates=core/build

- name: create log dir
  file: path={{ kafka['log_dir'] }} owner=kafka group=kafka state=directory

- name: server config
  template: src=server.properties.j2 dest={{ kafka['log_dir'] }}/config/server.properties owner=kafka group=kafka mode=755
  notify: restart kafka

- name: copy log config
  template: src=log4j.properties.j2 dest={{ kafka['log_dir'] }}/config/log4j.properties owner=kafka group=kafka mode=755
  notify: restart kafka

