tmp_dir: /tmp
install_dir: /opt
log_dir: /var/log
storm_version: 0.9.0.1

storm:
  url: "https://dl.dropboxusercontent.com/s/dj86w8ojecgsam7/storm-{{ storm_version }}.zip"
  archive: "{{ tmp_dir }}/storm-{{ storm_version }}.zip"
  home_dir: "{{ install_dir }}/storm-{{ storm_version }}"
  bin_dir: "{{ install_dir }}/storm-{{ storm_version }}/bin"
  data_dir: "{{ install_dir }}/storm-{{ storm_version }}/data"
  link: "{{ install_dir }}/storm"
  log_dir: "{{ log_dir }}/storm"

  zookeeper_root: /storm

  jmx_port: 9999
  ui_port: 8080
  logviewer_port: 8000
  slots_ports:
    - 6700
    - 6701
    - 6702
    - 6703

  user: storm
  group: storm
