- hosts: all
  remote_user: vagrant
  user: root
  sudo: true
  roles:
    - common

- hosts: zookeeper
  remote_user: vagrant
  user: root
  sudo: true
  roles:
    - zookeeper

- hosts: kafka
  remote_user: vagrant
  user: root
  sudo: true
  roles:
    - kafka

- hosts: storm_nimbus
 remote_user: vagrant
 user: root
 sudo: true
 roles:
   - storm_nimbus

- hosts: storm_supervisor
 remote_user: vagrant
 user: root
 sudo: true
 roles:
   - storm_supervisor


- hosts: redis
  remote_user: vagrant
  user: root
  sudo: true
  roles:
    - redis

- hosts: redis_commander
  remote_user: vagrant
  user: root
  sudo: true
  roles:
    - redis_commander