- hosts: all
  remote_user: vagrant
  user: root
  sudo: true
  roles:
    - common

- hosts: storm
  remote_user: vagrant
  user: root
  sudo: true
  roles:
    - storm

- hosts: storm_master
  remote_user: vagrant
  user: root
  sudo: true
  roles:
    - storm_master
