- hosts: all
  remote_user: vagrant
  user: root
  sudo: true
  vars_files:
    - vars.yml
  roles:
    - common

- hosts: zookeeper
  remote_user: vagrant
  user: root
  sudo: true
  vars_files:
    - vars.yml
  roles:
    - zookeeper

# - hosts: storm_master
#   remote_user: vagrant
#   user: root
#   sudo: true
#   vars_files:
#     - vars.yml
#     - roles/zookeeper/vars/main.yml
#   roles:
#   - storm-master

# - hosts: storm_slave
#   remote_user: vagrant
#   user: root
#   sudo: true
#   vars_files:
#     - vars.yml
#     - roles/zookeeper/vars/main.yml
#   roles:
#     - storm-slave