- hosts: all
  remote_user: vagrant
  user: root
  sudo: true
  roles:
    - common

- hosts: zookeeper
  remote_user: vagrant
  user: root
  sudo: true
  roles:
    - zookeeper

- hosts: storm_nimbus
  remote_user: vagrant
  user: root
  sudo: true
  roles:
    - storm_nimbus

- hosts: storm_supervisor
  remote_user: vagrant
  user: root
  sudo: true
  roles:
    - storm_supervisor

- hosts: kafka
  remote_user: vagrant
  user: root
  sudo: true
  roles:
    - kafka

- hosts: redis
  remote_user: vagrant
  user: root
  sudo: true
  roles:
    - redis