- hosts: all
  remote_user: vagrant
  user: root
  sudo: true
  vars_files:
    - vars.yml
  roles:
    - common

- hosts: zookeeper
  remote_user: vagrant
  user: root
  sudo: true
  vars_files:
    - vars.yml
  roles:
    - zookeeper