
tmp_dir: /tmp
install_dir: /opt
zookeeper_version: 3.4.5

zookeeper:
  url: "http://ftp.task.gda.pl/pub/www/apache/dist/zookeeper/zookeeper-{{ zookeeper_version }}/zookeeper-{{ zookeeper_version }}.tar.gz"
  archive: "{{ tmp_dir }}/zookeeper-{{ zookeeper_version }}.tar.gz"
  home_dir: "{{ install_dir }}/zookeeper-{{ zookeeper_version }}"
  bin_dir: "{{ install_dir }}/zookeeper-{{ zookeeper_version }}/bin"
  data_dir: "{{ install_dir }}/zookeeper-{{ zookeeper_version }}/data"
  link: "{{ install_dir }}/zookeeper"

  clientport: 2181
  leader_port: 2888
  election_port: 3888
  jmx_port: 9999
