
tmp_dir: /tmp
install_dir: /opt

zoo_version: 3.4.5
zookeeper_dir: "/opt/zookeeper"

zoo_url: "http://ftp.task.gda.pl/pub/www/apache/dist/zookeeper/zookeeper-{{ zoo_version }}/zookeeper-{{ zoo_version }}.tar.gz"
zoo_archive: "{{ tmp_dir }}/zookeeper-{{ zoo_version }}.tar.gz"

zookeeper:
  clientport: 2181
  leader_port: 2888
  election_port: 3888
  data_dir: "{{ install_dir }}/zookeeper-{{ zoo_version }}/data"
  jmx_port: 9999
