log_dir: /var/log
install_dir: /opt
kafka_version: "0.8.1"

kafka:
  url: "https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka-{{ kafka_version }}-src.tgz"
  archive: "{{ install_dir }}/kafka-{{ kafka_version }}-src.tgz"
  home_dir: "{{ install_dir }}/kafka-{{ kafka_version }}-src"
  link: "{{ install_dir }}/kafka"
  port: 7200
  log_dir: "{{ log_dir }}/kafka"
  log_file: "{{ log_dir }}/kafka/kafka.log"