install_dir: /opt
kafka_version: "0.8.2.0"
scala_version: "2.10"
kafka_with_version: "kafka_{{ scala_version }}-{{ kafka_version }}"
kafka_log_dir: "{{ install_dir }}/{{ kafka_with_version }}/logs"

kafka:
  url: "http://mirror.netcologne.de/apache.org/kafka/{{ kafka_version }}/{{ kafka_with_version }}.tgz"
  archive: "{{ install_dir }}/{{ kafka_with_version }}.tgz"
  home_dir: "{{ install_dir }}/{{ kafka_with_version }}"
  bin_dir: "{{ install_dir }}/{{ kafka_with_version }}/bin"
  link: "{{ install_dir }}/kafka"
  log_dir: "{{ kafka_log_dir }}"
  log_file: "{{ kafka_log_dir }}/kafka.log"

  port: 9092
  jmx_port: 9991
  kafka_heap_opts: -Xmx256M
  scala_version: scala_version

  user: kafka
  group: kafka
