log_dir: /var/log
install_dir: /opt
kafka_version: "0.8.1.1"

kafka:
  url: "https://github.com/apache/kafka/archive/{{ kafka_version }}.tar.gz"
  archive: "{{ install_dir }}/kafka-{{ kafka_version }}.tar.gz"
  home_dir: "{{ install_dir }}/kafka-{{ kafka_version }}"
  bin_dir: "{{ install_dir }}/kafka-{{ kafka_version }}/bin"
  link: "{{ install_dir }}/kafka"
  log_dir: "{{ install_dir }}/kafka/logs"
  log_file: "{{ log_dir }}/kafka/kafka.log"

  port: 9092
  jmx_port: 9999
  kafka_heap_opts: -Xmx256M
  scala_version: 2.8.0

  user: kafka
  group: kafka