- name: install libtool, autoconf, pkg-config
  apt: pkg={{ item }} state=present
  with_items:
    - libtool
    - autoconf
    - pkg-config

- name: fetch
  git: repo={{ jzmq['repo'] }} dest={{ jzmq['home_dir'] }} update=yes

- name: magic bug
  command: chdir={{ jzmq['home_dir'] }} sed -i 's/classdist_noinst.stamp/classnoinst.stamp/g' src/Makefile.am

- name: autogen
  command: chdir={{ jzmq['home_dir'] }} ./autogen.sh creates={{ jzmq['home_dir'] }}/configure

- name: configure
  command: chdir={{ jzmq['home_dir'] }} ./configure creates={{ jzmq['home_dir'] }}/Makefile
  environment:
    JAVA_HOME: "{{ jzmq['java_home'] }}"

- name: build
  command: chdir={{ jzmq['home_dir'] }} make creates={{ jzmq['home_dir'] }}/src/zmq.jar

- name: install
  command: chdir={{ jzmq['home_dir'] }} make install creates={{ jzmq['jar_dir'] }}/zmq.jar
